# Redirects
/sunzibingfa/privacy_policy       /sunzibingfa/privacy_policy.html
/lunyu/privacy_policy       /lunyu/privacy_policy.html
/sanguoyanyi/privacy_policy       /sanguoyanyi/privacy_policy.html
/xiyouji/privacy_policy       /xiyouji/privacy_policy.html
/hongloumeng/privacy_policy       /hongloumeng/privacy_policy.html
/shuihuzhuan/privacy_policy       /shuihuzhuan/privacy_policy.html
